import { AuthGuard } from './components/AurhGuard';
import { Header } from './components/Header';
import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>
          <Header />
          <main>{children}</main>
        </AuthGuard>
      </body>
    </html>
  );
}
